//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkTimeTracker.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"AAEAAAD/////AQAAAAAAAAAMAgAAAEZXb3JrVGltZVRyYWNrZXIsIFZlcnNpb249MS4wLjAuMCwgQ3VsdHVyZT1uZXV0cmFsLCBQdWJsaWNLZXlUb2tlbj1udWxsBAEAAACGAVN5c3RlbS5Db2xsZWN0aW9ucy5HZW5lcmljLkxpc3RgMVtbV29ya1RpbWVUcmFja2VyLlRocmVzaG9sZCwgV29ya1RpbWVUcmFja2VyLCBWZXJzaW9uPTEuMC4wLjAsIEN1bHR1cmU9bmV1dHJhbCwgUHVibGljS2V5VG9rZW49bnVsbF1dAwAAAAZfaXRlbXMFX3NpemUIX3ZlcnNpb24EAAAbV29ya1RpbWVUcmFja2VyLlRocmVzaG9sZFtdAgAAAAgICQMAAAADAAAAAAAAAAcDAAAAAAEAAAADAAAABBlXb3JrVGltZVRyYWNrZXIuVGhyZXNob2xkAgAAAAkEAAAACQUAAAAJBgAAAAUEAAAAGVdvcmtUaW1lVHJhY2tlci5UaHJlc2hvbGQDAAAABV9uYW1lBl9jb2xvcgZfdmFsdWUBBAAWV29ya1RpbWVUcmFja2VyLkNvbG91cgIAAAAIAgAAAAYHAAAAA2JhZAX4////FldvcmtUaW1lVHJhY2tlci5Db2xvdXIEAAAAAUEBUgFHAUIAAAAAAgICAgIAAAD//wAAAAAAAAEFAAAABAAAAAYJAAAABm1lZGl1bQH2////+P//////gEAyAAAAAQYAAAAEAAAABgsAAAAEZ29vZAH0////+P////9BwRxQAAAACw==")]
        public string listThresholds {
            get {
                return ((string)(this["listThresholds"]));
            }
            set {
                this["listThresholds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"AAEAAAD/////AQAAAAAAAAAMAgAAAEZXb3JrVGltZVRyYWNrZXIsIFZlcnNpb249MS4wLjAuMCwgQ3VsdHVyZT1uZXV0cmFsLCBQdWJsaWNLZXlUb2tlbj1udWxsBAEAAACCAVN5c3RlbS5Db2xsZWN0aW9ucy5HZW5lcmljLkxpc3RgMVtbV29ya1RpbWVUcmFja2VyLkJyZWFrLCBXb3JrVGltZVRyYWNrZXIsIFZlcnNpb249MS4wLjAuMCwgQ3VsdHVyZT1uZXV0cmFsLCBQdWJsaWNLZXlUb2tlbj1udWxsXV0DAAAABl9pdGVtcwVfc2l6ZQhfdmVyc2lvbgQAABdXb3JrVGltZVRyYWNrZXIuQnJlYWtbXQIAAAAICAkDAAAAAwAAAAAAAAAHAwAAAAABAAAAAwAAAAQVV29ya1RpbWVUcmFja2VyLkJyZWFrAgAAAAkEAAAACQUAAAAJBgAAAAUEAAAAFVdvcmtUaW1lVHJhY2tlci5CcmVhawQAAAAFX25hbWUIX2VuYWJsZWQJX2R1cmF0aW9uCl9zdGFydHRpbWUBAAAAAQwNAgAAAAYHAAAACWJyZWFrZmFzdAEAGnEYAgAAAACQdCzQA9SIAQUAAAAEAAAABggAAAAFbHVuY2gBADTiMAQAAAAAyMFR6QPUiAEGAAAABAAAAAYJAAAABmRpbm5lcgEAGnEYAgAAAAA4XJwbBNSICw==")]
        public string listBreaks {
            get {
                return ((string)(this["listBreaks"]));
            }
            set {
                this["listBreaks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"AAEAAAD/////AQAAAAAAAAAMAgAAAEZXb3JrVGltZVRyYWNrZXIsIFZlcnNpb249MS4wLjAuMCwgQ3VsdHVyZT1uZXV0cmFsLCBQdWJsaWNLZXlUb2tlbj1udWxsBAEAAACFAVN5c3RlbS5Db2xsZWN0aW9ucy5HZW5lcmljLkxpc3RgMVtbV29ya1RpbWVUcmFja2VyLlN1YnRpdGxlLCBXb3JrVGltZVRyYWNrZXIsIFZlcnNpb249MS4wLjAuMCwgQ3VsdHVyZT1uZXV0cmFsLCBQdWJsaWNLZXlUb2tlbj1udWxsXV0DAAAABl9pdGVtcwVfc2l6ZQhfdmVyc2lvbgQAABpXb3JrVGltZVRyYWNrZXIuU3VidGl0bGVbXQIAAAAICAkDAAAACQAAAAAAAAAHAwAAAAABAAAACQAAAAQYV29ya1RpbWVUcmFja2VyLlN1YnRpdGxlAgAAAAkEAAAACQUAAAAJBgAAAAkHAAAACQgAAAAJCQAAAAkKAAAACQsAAAAJDAAAAAUEAAAAGFdvcmtUaW1lVHJhY2tlci5TdWJ0aXRsZQMAAAALX3Jhbmdlc3RhcnQJX3JhbmdlZW5kCV9zdWJ0aXRsZQAAAQgIAgAAAAAAAAAKAAAABg0AAAATR29vZCBtb3JuaW5nLCBjdW50IQEFAAAABAAAAAAAAAAKAAAABg4AAAAQU3RpbGwgZHJ1bmssIGVoPwEGAAAABAAAAAoAAAAyAAAABg8AAAARWW91J3JlIGRvb21lZC4uLi4BBwAAAAQAAAAKAAAAMgAAAAYQAAAAEkV0ZXJuaXR5IGF3YWl0cy4uLgEIAAAABAAAADIAAABaAAAABhEAAAAZQmVlciBpcyBnZXR0aW5nIGNsb3Nlci4uLgEJAAAABAAAADIAAABaAAAABhIAAAAWSnV1dXVzdCBhIGJpdCBtb3JlIG5vdwEKAAAABAAAAFoAAABkAAAABhMAAAAJRU5EUFNVUlQhAQsAAAAEAAAAZAAAAGQAAAAGFAAAABFGdWNrIG9mZiBhbHJlYWR5IQEMAAAABAAAAGQAAABkAAAABhUAAAAPR2V0IGxvc3QsIGN1bnQhCw==")]
        public string listSubtitles {
            get {
                return ((string)(this["listSubtitles"]));
            }
            set {
                this["listSubtitles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"AAEAAAD/////AQAAAAAAAAAMAgAAAEZXb3JrVGltZVRyYWNrZXIsIFZlcnNpb249MS4wLjAuMCwgQ3VsdHVyZT1uZXV0cmFsLCBQdWJsaWNLZXlUb2tlbj1udWxsBAEAAACAAVN5c3RlbS5Db2xsZWN0aW9ucy5HZW5lcmljLkxpc3RgMVtbV29ya1RpbWVUcmFja2VyLkRheSwgV29ya1RpbWVUcmFja2VyLCBWZXJzaW9uPTEuMC4wLjAsIEN1bHR1cmU9bmV1dHJhbCwgUHVibGljS2V5VG9rZW49bnVsbF1dAwAAAAZfaXRlbXMFX3NpemUIX3ZlcnNpb24EAAAVV29ya1RpbWVUcmFja2VyLkRheVtdAgAAAAgICQMAAAAAAAAAAAAAAAcDAAAAAAEAAAAAAAAABBNXb3JrVGltZVRyYWNrZXIuRGF5AgAAAAs=")]
        public string listDays {
            get {
                return ((string)(this["listDays"]));
            }
            set {
                this["listDays"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("456")]
        public int intWorkDuration {
            get {
                return ((int)(this["intWorkDuration"]));
            }
            set {
                this["intWorkDuration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int intInterval {
            get {
                return ((int)(this["intInterval"]));
            }
            set {
                this["intInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime dtWorkStartTime {
            get {
                return ((global::System.DateTime)(this["dtWorkStartTime"]));
            }
            set {
                this["dtWorkStartTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime dtWorkEndTime {
            get {
                return ((global::System.DateTime)(this["dtWorkEndTime"]));
            }
            set {
                this["dtWorkEndTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan tsWorkTimeRemaining {
            get {
                return ((global::System.TimeSpan)(this["tsWorkTimeRemaining"]));
            }
            set {
                this["tsWorkTimeRemaining"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan tsWorkTimeElapsed {
            get {
                return ((global::System.TimeSpan)(this["tsWorkTimeElapsed"]));
            }
            set {
                this["tsWorkTimeElapsed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AAEAAAD/////AQAAAAAAAAAMAgAAAEZXb3JrVGltZVRyYWNrZXIsIFZlcnNpb249MS4wLjAuMCwgQ3Vsd" +
            "HVyZT1uZXV0cmFsLCBQdWJsaWNLZXlUb2tlbj1udWxsBQEAAAAWV29ya1RpbWVUcmFja2VyLkNvbG91c" +
            "gQAAAABQQFSAUcBQgAAAAACAgICAgAAAP////8L")]
        public string colorTrayIcon {
            get {
                return ((string)(this["colorTrayIcon"]));
            }
            set {
                this["colorTrayIcon"] = value;
            }
        }
    }
}
