//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkTimeTracker.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"AAEAAAD/////AQAAAAAAAAAMAgAAAEZXb3JrVGltZVRyYWNrZXIsIFZlcnNpb249MS4wLjAuMCwgQ3VsdHVyZT1uZXV0cmFsLCBQdWJsaWNLZXlUb2tlbj1udWxsBAEAAACGAVN5c3RlbS5Db2xsZWN0aW9ucy5HZW5lcmljLkxpc3RgMVtbV29ya1RpbWVUcmFja2VyLlRocmVzaG9sZCwgV29ya1RpbWVUcmFja2VyLCBWZXJzaW9uPTEuMC4wLjAsIEN1bHR1cmU9bmV1dHJhbCwgUHVibGljS2V5VG9rZW49bnVsbF1dAwAAAAZfaXRlbXMFX3NpemUIX3ZlcnNpb24EAAAbV29ya1RpbWVUcmFja2VyLlRocmVzaG9sZFtdAgAAAAgICQMAAAADAAAAAwAAAAcDAAAAAAEAAAAEAAAABBlXb3JrVGltZVRyYWNrZXIuVGhyZXNob2xkAgAAAAkEAAAACQUAAAAJBgAAAAoFBAAAABlXb3JrVGltZVRyYWNrZXIuVGhyZXNob2xkAwAAAAdzdHJOYW1lBmNDb2xvcgZpVmFsdWUBBAAWV29ya1RpbWVUcmFja2VyLkNvbG91cgIAAAAIAgAAAAYHAAAAA2JhZAX4////FldvcmtUaW1lVHJhY2tlci5Db2xvdXIEAAAAAUEBUgFHAUIAAAAAAgICAgIAAAD//wAAAAAAAAEFAAAABAAAAAYJAAAABGdvb2QB9v////j/////QcEcUAAAAAEGAAAABAAAAAYLAAAABm1lZGl1bQH0////+P//////gEAyAAAACw==")]
        public string listThresholds {
            get {
                return ((string)(this["listThresholds"]));
            }
            set {
                this["listThresholds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"AAEAAAD/////AQAAAAAAAAAMAgAAAEZXb3JrVGltZVRyYWNrZXIsIFZlcnNpb249MS4wLjAuMCwgQ3VsdHVyZT1uZXV0cmFsLCBQdWJsaWNLZXlUb2tlbj1udWxsBAEAAACCAVN5c3RlbS5Db2xsZWN0aW9ucy5HZW5lcmljLkxpc3RgMVtbV29ya1RpbWVUcmFja2VyLkJyZWFrLCBXb3JrVGltZVRyYWNrZXIsIFZlcnNpb249MS4wLjAuMCwgQ3VsdHVyZT1uZXV0cmFsLCBQdWJsaWNLZXlUb2tlbj1udWxsXV0DAAAABl9pdGVtcwVfc2l6ZQhfdmVyc2lvbgQAABdXb3JrVGltZVRyYWNrZXIuQnJlYWtbXQIAAAAICAkDAAAAAwAAAAMAAAAHAwAAAAABAAAABAAAAAQVV29ya1RpbWVUcmFja2VyLkJyZWFrAgAAAAkEAAAACQUAAAAJBgAAAAoFBAAAABVXb3JrVGltZVRyYWNrZXIuQnJlYWsEAAAAB3N0ck5hbWUJaXNFbmFibGVkCnRzRHVyYXRpb24LZHRTdGFydFRpbWUBAAAAAQwNAgAAAAYHAAAACWJyZWFrZmFzdAEAGnEYAgAAAACQdCzQA9QIAQUAAAAEAAAABggAAAAFbHVuY2gBADTiMAQAAAAAyMFR6QPUCAEGAAAABAAAAAYJAAAABmRpbm5lcgEAGnEYAgAAAAA4XJwbBNQICw==")]
        public string listBreaks {
            get {
                return ((string)(this["listBreaks"]));
            }
            set {
                this["listBreaks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"AAEAAAD/////AQAAAAAAAAAMAgAAAEZXb3JrVGltZVRyYWNrZXIsIFZlcnNpb249MS4wLjAuMCwgQ3VsdHVyZT1uZXV0cmFsLCBQdWJsaWNLZXlUb2tlbj1udWxsBAEAAACFAVN5c3RlbS5Db2xsZWN0aW9ucy5HZW5lcmljLkxpc3RgMVtbV29ya1RpbWVUcmFja2VyLlN1YnRpdGxlLCBXb3JrVGltZVRyYWNrZXIsIFZlcnNpb249MS4wLjAuMCwgQ3VsdHVyZT1uZXV0cmFsLCBQdWJsaWNLZXlUb2tlbj1udWxsXV0DAAAABl9pdGVtcwVfc2l6ZQhfdmVyc2lvbgQAABpXb3JrVGltZVRyYWNrZXIuU3VidGl0bGVbXQIAAAAICAkDAAAACQAAAAkAAAAHAwAAAAABAAAAEAAAAAQYV29ya1RpbWVUcmFja2VyLlN1YnRpdGxlAgAAAAkEAAAACQUAAAAJBgAAAAkHAAAACQgAAAAJCQAAAAkKAAAACQsAAAAJDAAAAA0HBQQAAAAYV29ya1RpbWVUcmFja2VyLlN1YnRpdGxlAwAAAAtpUmFuZ2VTdGFydAlpUmFuZ2VFbmQLc3RyU3VidGl0bGUAAAEICAIAAAAAAAAACgAAAAYNAAAAE0dvb2QgbW9ybmluZywgY3VudCEBBQAAAAQAAAAAAAAACgAAAAYOAAAAEFN0aWxsIGRydW5rLCBlaD8BBgAAAAQAAAAKAAAAMgAAAAYPAAAAEVlvdSdyZSBkb29tZWQuLi4uAQcAAAAEAAAACgAAADIAAAAGEAAAABJFdGVybml0eSBhd2FpdHMuLi4BCAAAAAQAAAAyAAAAWgAAAAYRAAAAGUJlZXIgaXMgZ2V0dGluZyBjbG9zZXIuLi4BCQAAAAQAAAAyAAAAWgAAAAYSAAAAFkp1dXV1c3QgYSBiaXQgbW9yZSBub3cBCgAAAAQAAABaAAAAZAAAAAYTAAAACUVORFBTVVJUIQELAAAABAAAAGQAAABkAAAABhQAAAARRnVjayBvZmYgYWxyZWFkeSEBDAAAAAQAAABkAAAAZAAAAAYVAAAAD0dldCBsb3N0LCBjdW50IQs=")]
        public string listSubtitles {
            get {
                return ((string)(this["listSubtitles"]));
            }
            set {
                this["listSubtitles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"AAEAAAD/////AQAAAAAAAAAMAgAAAEZXb3JrVGltZVRyYWNrZXIsIFZlcnNpb249MS4wLjAuMCwgQ3VsdHVyZT1uZXV0cmFsLCBQdWJsaWNLZXlUb2tlbj1udWxsBAEAAACAAVN5c3RlbS5Db2xsZWN0aW9ucy5HZW5lcmljLkxpc3RgMVtbV29ya1RpbWVUcmFja2VyLkRheSwgV29ya1RpbWVUcmFja2VyLCBWZXJzaW9uPTEuMC4wLjAsIEN1bHR1cmU9bmV1dHJhbCwgUHVibGljS2V5VG9rZW49bnVsbF1dAwAAAAZfaXRlbXMFX3NpemUIX3ZlcnNpb24EAAAVV29ya1RpbWVUcmFja2VyLkRheVtdAgAAAAgICQMAAAABAAAAAQAAAAcDAAAAAAEAAAAEAAAABBNXb3JrVGltZVRyYWNrZXIuRGF5AgAAAAkEAAAADQMFBAAAABNXb3JrVGltZVRyYWNrZXIuRGF5AwAAAAtkdFN0YXJ0VGltZQlkdEVuZFRpbWUDaUlEAAAADQ0IAgAAAADWJASO79QIACKgStrv1AgBAAAACw==")]
        public string listDays {
            get {
                return ((string)(this["listDays"]));
            }
            set {
                this["listDays"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("456")]
        public int intWorkDuration {
            get {
                return ((int)(this["intWorkDuration"]));
            }
            set {
                this["intWorkDuration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int intInterval {
            get {
                return ((int)(this["intInterval"]));
            }
            set {
                this["intInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime dtWorkStartTime {
            get {
                return ((global::System.DateTime)(this["dtWorkStartTime"]));
            }
            set {
                this["dtWorkStartTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime dtWorkEndTime {
            get {
                return ((global::System.DateTime)(this["dtWorkEndTime"]));
            }
            set {
                this["dtWorkEndTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan tsWorkTimeRemaining {
            get {
                return ((global::System.TimeSpan)(this["tsWorkTimeRemaining"]));
            }
            set {
                this["tsWorkTimeRemaining"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan tsWorkTimeElapsed {
            get {
                return ((global::System.TimeSpan)(this["tsWorkTimeElapsed"]));
            }
            set {
                this["tsWorkTimeElapsed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AAEAAAD/////AQAAAAAAAAAMAgAAAEZXb3JrVGltZVRyYWNrZXIsIFZlcnNpb249MS4wLjAuMCwgQ3Vsd" +
            "HVyZT1uZXV0cmFsLCBQdWJsaWNLZXlUb2tlbj1udWxsBQEAAAAWV29ya1RpbWVUcmFja2VyLkNvbG91c" +
            "gQAAAABQQFSAUcBQgAAAAACAgICAgAAAP////8L")]
        public string colorTrayIcon {
            get {
                return ((string)(this["colorTrayIcon"]));
            }
            set {
                this["colorTrayIcon"] = value;
            }
        }
    }
}
